# Numpy

Es un paquete de computación científica que contiene muchas funciones para haer cálculos entre vectores y matrices de forma muy eficiente, entre los que se encuentran:

1. Funciones de álgebra lineal
2. Transformadas de fourier
3. Generación de números aleatorios

Numpy es considerado por muchas personas como el equivalente a MATLAB, incluso más potente y con la ventaja que es gratuito.

Adicionalmente NUMPY es usado por organizaciones como la NASA, Los Alamos y JPMorgan en tareas que cubren lo científico a lo financiero.

Para conocer más: https://numpy.org/

## Arrays

Un array o un arreglo es un vector, muy similar a una lista en python, con la diferencia que, como hablamos antes, esta librería es muy eficiente.

In [1]:
import numpy as np

In [2]:
vector = np.array([0,1,2,3])
vector

array([0, 1, 2, 3])

## Eficiencia

In [3]:
## Python
L = range(1000)
%timeit [i**2 for i in L]

201 µs ± 3.04 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [4]:
a = np.arange(1000)
%timeit a**2

1.25 µs ± 12.2 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [5]:
eficiencia = 201/1.25
print("veces más rápido np vs python ()".format(eficiencia))

veces más rápido np vs python ()


## Manipulando arrays en NUMPY

a[inicio:fin] # items desde inicio hasta fin-1
a[inicio:] # items desde el inicio hasta el final del array
a[:fin] # items desde el principio hasta fin-1
a[:] # apuntamos hacia la memoria donde está el array

In [2]:
vector = np.arange(10)
vector

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
print(vector[1:3])
print(vector[2:])
print(vector[:8])

[1 2]
[2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7]


In [5]:
a=vector[:]
b=np.copy(vector)

In [6]:
vector[0]=89

In [7]:
print(vector)
print(a)
print(b)

[89  1  2  3  4  5  6  7  8  9]
[89  1  2  3  4  5  6  7  8  9]
[0 1 2 3 4 5 6 7 8 9]


## Operaciones básicas

In [8]:
vector

array([89,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [10]:
a = np.arange(10)
b = np.arange(20,30)
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[20 21 22 23 24 25 26 27 28 29]


In [11]:
c = a + b
c

array([20, 22, 24, 26, 28, 30, 32, 34, 36, 38])

In [13]:
d = a -b
d

array([-20, -20, -20, -20, -20, -20, -20, -20, -20, -20])

In [15]:
e = a * b
e

array([  0,  21,  44,  69,  96, 125, 156, 189, 224, 261])

In [16]:
f = a / b
f

array([0.        , 0.04761905, 0.09090909, 0.13043478, 0.16666667,
       0.2       , 0.23076923, 0.25925926, 0.28571429, 0.31034483])

## Operaciones avanzadas

In [ ]:
# Producto punto entre dos vectores da como resul